-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Chimei Innolux Corporation 0x14B1",
  mode = "1920x1080@60.01",
  position = "0x0",
  scale = 1.5,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Chimei Innolux Corporation 0x14B1", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Chimei Innolux Corporation 0x14B1" })
